Models/VatPercentage.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VoorraadSysteem.Models
{
	public class VatPercentage
	{
		[Key]
		public int Id { get; set; }
		[Required]
		public int Percentage { get; set; }
		public ICollection<TicketsProducts> TicketsProducts { get; set; }
	}
}

Controllers/VatPercentageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VoorraadSysteem.Data.UnitOfWork;
using VoorraadSysteem.Models;
using VoorraadSysteem.ViewModels;

namespace VoorraadSysteem.Controllers
{
	
	public class VatPercentageController : Controller
	{
		private readonly IUnitOfWork _uow;
		public VatPercentageController(IUnitOfWork uow) { _uow = uow; }
		[Authorize(Roles = "Gebruiker, Admin")]
		public IActionResult Index()
		{
			VatPercentageListViewModel viewModel = new VatPercentageListViewModel();
			viewModel.VatPercentages = _uow.VatPercentageRepository.All().ToList();
			return View(viewModel);
		}
		[Authorize(Roles = "Gebruiker, Admin")]
		public IActionResult Search(VatPercentageListViewModel viewModel)
		{
			if (viewModel.VatPercentageSearch>=0)
			{
				viewModel.VatPercentages = _uow.VatPercentageRepository.Search().Where(v => v.Percentage == viewModel.VatPercentageSearch).ToList();
			}
			else
			{
				viewModel.VatPercentages = _uow.VatPercentageRepository.All().ToList();
			}
			return View("index", viewModel);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult Create()
		{
			CreateVatPercentageViewModel viewModel = new CreateVatPercentageViewModel();
			return View(viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Create(CreateVatPercentageViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				_uow.VatPercentageRepository.Add(new VatPercentage()
				{
					Percentage = viewModel.Percentage
				});
				await _uow.Save();
				return RedirectToAction(nameof(Index));
			}
			return View(viewModel);
		}
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var vatPercentage = await _uow.VatPercentageRepository.Find((int)id);
			if (vatPercentage == null)
			{
				return NotFound();
			}

			EditVatPercentageViewModel viewModel = new EditVatPercentageViewModel()
			{
				Id = vatPercentage.Id,
				Percentage = vatPercentage.Percentage,
			};
			return View(viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int id, EditVatPercentageViewModel viewModel)
		{
			if (id != viewModel.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					VatPercentage vatPercentage = await _uow.VatPercentageRepository.Find(id);
					vatPercentage.Percentage = viewModel.Percentage;
					_uow.VatPercentageRepository.Update(vatPercentage);
					await _uow.Save();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!_uow.VatPercentageRepository.Search().Any(s => s.Id == viewModel.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(viewModel);
		}
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var vatPercentage = await _uow.VatPercentageRepository.Find((int)id);
			if (vatPercentage == null)
			{
				return NotFound();
			}

			DeleteVatPercentageViewModel viewModel = new DeleteVatPercentageViewModel()
			{
				Id = vatPercentage.Id,
				Percentage = vatPercentage.Percentage
			};
			return View(viewModel);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmed(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var user = await _uow.VatPercentageRepository.Find((int)id);
			if (user == null)
			{
				return NotFound();
			}

			_uow.VatPercentageRepository.Delete(user);
			await _uow.Save();
			return RedirectToAction(nameof(Index));
		}
	}
}

Views/Vatpercentage/Create.cshtml
@model VoorraadSysteem.ViewModels.CreateVatPercentageViewModel

@{
	ViewData["Title"] = "Nieuw BTW percentage aanmaken";
}

<h1>Nieuw BTW percentage aanmaken</h1>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Percentage" class="control-label">Percentage</label>
				<input asp-for="Percentage" class="form-control" />
				<span asp-validation-for="Percentage" class="text-danger"></span>
			</div>			
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Ga terug naar de lijst</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Vatpercentage/Delete.cshtml
@model VoorraadSysteem.ViewModels.DeleteVatPercentageViewModel

@{
	ViewData["Title"] = Model.Percentage + "% verwijderen";
}

<h1>@Model.Percentage% verwijderen</h1>
<h4>Ben je zeker dat je @Model.Percentage% wilt verwijderen?</h4>
<hr />
<form asp-action="Delete">
	<input type="hidden" asp-for="Id" />
	<input type="submit" value="Delete" class="btn btn-primary" /> | <a asp-action="Index">Ga terug naar de lijst</a>
</form>

Views/Vatpercentage/Edit.cshtml
@model VoorraadSysteem.ViewModels.EditVatPercentageViewModel

@{
	ViewData["Title"] = "BTW percentage aanpassen";
}

<h1>@Model.Percentage aanpassen</h1>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<input type="hidden" asp-for="Id" />
			</div>			
			<div class="form-group">
				<label asp-for="Percentage" class="control-label">Percentage</label>
				<input asp-for="Percentage" class="form-control" />
				<span asp-validation-for="Percentage" class="text-danger"></span>
			</div>			
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Ga terug naar de lijst</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Views/Vatpercentage/Index.cshtml
@model VoorraadSysteem.ViewModels.VatPercentageListViewModel
@{
	ViewData["Title"] = "BTW lijst";
}

<h1>Lijst BTW percentages</h1>
<hr />
<form asp-controller="VatPercentage" asp-action="Search" method="get">
	<div class="form-actions no-color">
		<p>
			Zoek op BTW percentage:
			<input asp-for="VatPercentageSearch" type="text" value=""/>
			<input type="submit" value="Zoeken" class="btn btn-default"/>
			<a asp-controller="VatPercentage" asp-action="Index">Terug naar volledige lijst</a>
		</p>
	</div>
</form>

<table>
	<thead>
		<tr>
			<th class="col-md-6">
				@Html.DisplayNameFor(model => model.VatPercentages.First().Percentage)
			</th>
		</tr>
	</thead>
	<tbody>
		@{
			if (Model.VatPercentages.Count>0)
			{
				foreach (var percent in Model.VatPercentages)
				{
					<tr>
						<td class="col-md-6">
							@percent.Percentage
						</td>
						<td class="col-md-6">
							@{
								if (User.IsInRole("Admin"))
								{
									<a asp-action="Edit" asp-route-id="@percent.Id">Wijzig</a> <a asp-action="Delete" asp-route-id="@percent.Id">Delete</a>
								}
							}					
						</td>
					</tr>
				}
			}
			else
			{
				<tr>
					<td class="col-md-12">
						Er is geen percentage gevonden.
					</td>
				</tr>
			}
		}
	</tbody>
</table>

<div class="position-absolute fake-add-button" id="add-button">
	<a asp-action="Create">
		<i class="bi bi-plus-lg" style="font-size: 50px;"></i>
	</a>	
</div>